# Generated by Django 4.0.1 on 2022-04-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('societe', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('sujet', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
