# Generated by Django 4.0.1 on 2022-07-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('video_url', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
            ],
        ),
    ]
