# Generated by Django 4.0.1 on 2022-07-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopartenaire',
            name='actif',
            field=models.BooleanField(default=1),
        ),
    ]
