# Generated by Django 4.0.1 on 2022-02-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposant', '0003_categorie_is_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='nom_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
